### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by PaperChonChon** [PortSwigger/param-miner#12]
Hi,

I followed the online guide on how to go about executing it which is to use right click > Guess header/cookie/param. However, when I did that, there is no activity on my Burp.
Burp version tested: 
2.0.13beta Pro
1.7.37 Pro
1.7.27 Pro
OS: Windows 10
Java: 
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

Steps to reproduce:

1) Used Burp versions mentioned above
2) Install Param Miner from BApp store
3) Select the request -> Right click ->Guess GET Header -> OK

Nothing happens.
Extension output in Extender tab contains the usual stuff, no output in Errors tab.
There is an error that appeared in command prompt when running Burp through it, shown below:
`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at burp.Keysmith.parseParam(Keysmith.java:74)
        at burp.Keysmith.getParamKeys(Keysmith.java:57)
        at burp.Keysmith.getAllKeys(Keysmith.java:46)
        at burp.ParamAttack.calculatePayloads(ParamAttack.java:298)
        at burp.ParamAttack.<init>(ParamAttack.java:107)
        at burp.ParamGuesser.run(ParamGuesser.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`
I have tried changing the max bucket size and forced bucket size to other values knowing the comma and space cause problems but to no avail. 
All values of Param Miner are left at default. I have also tried disabling every checkbox, same result.
No result in the scan result or anywhere.

Please advise, thank you!

**Comment by PaperChonChon** [comment]
I also noticed that the X-Forwarded-Ssl header has an extra space after Ssl, which can causes the server to respond an error page

**Comment by albinowax** [comment]
The X-Forwarded-Ssl issue should be fixed in the latest release.

I have verified param miner can handle paths with %20, I don't think this is likely to be the root issue. If you find a URL you can reliably replicate this problem on, please file a new issue with it.
