### ISSUE TITLE
Requests doesn't send to target.

### ISSUE THREAD

**Issue by blacksper** [PortSwigger/param-miner#2]
Hello.
The problem is that when I installed extension Param Miner and ran it, it doesn't send any requests to selected request(I installed logger++ and Flow extensions to test it).

Burp version: 1.7.37
OS: Windows 10
java --version output:
`java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)`

Steps to reproduce:
1) Install burp 1.7.37
2) Install Param Miner from bapp store
3) Select the request -> Right click ->Guess GET Parameters-> OK
4) *Nothing happens*

Extension output in Extender tab contain only:
`Add fixed cachebuster: true
Add dynamic cachebuster: false
learn observed words: false
skip boring words: true
only report unique params: false
response: true
use basic wordlist: true
use bonus wordlist: true
bruteforce: true
skip uncacheable: false
dynamic keyload: false
max one per host: false
max one per host+status: false
scan identified params: false
auto-mine proxy traffic: false
auto-nest params: false
try cache poison: true
try method flip: false
thread pool size: 8
rotation interval: 200
rotation increment: 4
force bucketsize: -1
max bucketsize: 65536
max param length: 32
Loaded Param Miner v1.04
    CACHE_ONLY false
`

**Comment by albinowax** [comment]
That's odd - it works fine on windows 10 for me. Is the 'Errors' tab entirely blank? Could you try launching Burp from the cmd prompt, and see if any errors appear there?

**Comment by albinowax** [comment]
Also, I assume it doesn't work on any websites at all for you? Feel free to try it out on https://hackxor.net/

**Comment by blacksper** [comment]
Error tab is empty. It doesn't work for any websites. 
When I ran burp via cmd it show me error when I click to "OK" in checkboxes popup.
Output:
`java.lang.NumberFormatException: For input string: "65 536"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at burp.ConfigurableSettings.showSettings(Utilities.java:235)
        at burp.TriggerParamGuesser.actionPerformed(TriggerParamGuesser.java:31)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

This is default view of pop after clicking "Guess GET parameters"
![screen](https://user-images.githubusercontent.com/18604392/44043006-72d268c6-9f2a-11e8-8454-554284df77f0.PNG)

**Comment by blacksper** [comment]
I solved the problem. It's neccessary to set "max bucketsize"=999. But if I set the biggest number the problem still exists.

**Comment by albinowax** [comment]
That would explain the problem - your locale might be using spaces, whereas mine uses commas

**Comment by albinowax** [comment]
Right, this should fix it: https://github.com/PortSwigger/param-miner/commit/df235bc67891f8524af02cf0e6b8538093104e29

**Comment by WHHackersBR** [comment]
I am having the same problem using the extension on Mac.
<img width="345" alt="captura de tela 2018-09-11 as 22 34 10" src="https://user-images.githubusercontent.com/6765546/45396591-d55b5800-b612-11e8-92c4-ea1a11f0886a.png">

**Comment by albinowax** [comment]
OK your local is using dots... I'm just going to strip all non-numeric characters

**Comment by albinowax** [comment]
Alright, fixed now: https://github.com/PortSwigger/param-miner/commit/e30561faf3ac103405e1e7a229e5c43d07602e7e
