### ISSUE TITLE
Won't launch on Mac

### ISSUE THREAD

**Issue by David-Gilman** [PortSwigger/param-miner#6]
When I load the App through the store, Burp says that it's loaded successfully but I get the following error message and I can't see it the extension when right clicking requests.

```
java.lang.NoSuchMethodError
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at burp.cke.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by homeyer** [comment]
I'm running v1.7.37 of Burp Suite Pro and was able to install it fine via the Extender -> BApp Store. OSX 10.11.5.
