### ISSUE TITLE
Param Miner Slow / Out of Memory

### ISSUE THREAD

**Issue by albinowax** [PortSwigger/param-miner#82]
I have the same issue. After initiating a scan/attack, Burp becomes largely unresponsive for about 2-3 minutes while the attacks are queued. I will try to reproduce against Gin and Juice Shop in a clean environment.

Burp 2022.12.6 on Ubuntu
OpenJDK 17.0.5
albinowaxUtils v1.03
Param Miner v1.4d

I have the below error logged, but I didn't correlate it with the slowdown. 
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.addAll(ArrayList.java:678)
	at burp.Keysmith.getJsonKeys(Keysmith.java:184)
	at burp.Keysmith.getJsonKeys(Keysmith.java:169)
	at burp.Keysmith.getJsonKeys(Keysmith.java:23)
	at burp.ParamGrabber.saveParams(ParamGrabber.java:63)
	at burp.ParamGrabber.processProxyMessage(ParamGrabber.java:45)
	at burp.cp7.handleReceivedResponse(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.qyv.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy83.handleReceivedResponse(Unknown Source)
	at burp.m7e.W(Unknown Source)
	at burp.c0c.J(Unknown Source)
	at burp.gdi$$Lambda$1878/0x000000080196b428.p(Unknown Source)
	at burp.gdi.N(Unknown Source)
	at burp.gdi.e(Unknown Source)
	at burp.gdi.u(Unknown Source)
	at burp.n05.T(Unknown Source)
	at burp.n05.z(Unknown Source)
	at burp.nz8.I(Unknown Source)
	at burp.nze.z(Unknown Source)
	at burp.nze.f(Unknown Source)
	at burp.nze.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(HashMap.java:702)
	at java.base/java.util.HashMap.putVal(HashMap.java:627)
	at java.base/java.util.HashMap.put(HashMap.java:610)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
	at java.base/java.util.HashSet.<init>(HashSet.java:121)
	at burp.Keysmith.getWords(Keysmith.java:99)
	at burp.ParamGrabber.saveParams(ParamGrabber.java:58)
	at burp.ParamGrabber.processProxyMessage(ParamGrabber.java:45)
	at burp.cp7.handleReceivedResponse(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.qyv.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy83.handleReceivedResponse(Unknown Source)
	at burp.m7e.W(Unknown Source)
	at burp.c0c.J(Unknown Source)
	at burp.gdi$$Lambda$1878/0x000000080196b428.p(Unknown Source)
	at burp.gdi.N(Unknown Source)
	at burp.gdi.e(Unknown Source)
	at burp.gdi.u(Unknown Source)
	at burp.n05.T(Unknown Source)
	at burp.n05.z(Unknown Source)
	at burp.nz8.I(Unknown Source)
	at burp.nze.z(Unknown Source)
	at burp.nze.f(Unknown Source)
	at burp.nze.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

_Originally posted by @ryarmst in https://github.com/PortSwigger/param-miner/issues/62#issuecomment-1402770779_

**Comment by ryarmst** [comment]
I have not been able to reliably replicate. I think it may actually be some impact that pausing a guest VM has on the JVM. As such, I think the issue can be safely closed.

**Comment by albinowax** [comment]
Cool, will do.
