### ISSUE TITLE
java.lang.UnsupportedOperationException: Action is not supported for this parameter type

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/param-miner#9]
I have a request of "Content-Type: application/soap+xml;charset=UTF-8"
When I try "Guess XML parameter", "" I receive this error:

```
java.lang.UnsupportedOperationException: Action is not supported for this parameter type
	at burp.t5b.a(Unknown Source)
	at burp.t5b.removeParameter(Unknown Source)
	at burp.t5b.updateParameter(Unknown Source)
	at burp.zjb.updateParameter(Unknown Source)
	at burp.ParamNameInsertionPoint.buildBasicRequest(BurpExtender.java:427)
	at burp.ParamNameInsertionPoint.buildRequest(BurpExtender.java:365)
	at burp.PayloadInjector.probeAttack(PayloadInjector.java:153)
	at burp.ParamAttack.updateBaseline(ParamAttack.java:264)
	at burp.ParamAttack.<init>(ParamAttack.java:135)
	at burp.ParamGuesser.run(ParamGuesser.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by albinowax** [comment]
Thanks for the report, unfortunately that's a Burp limitation - not much I can do about that.
